include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= How to monitor campaign progress

== Introduction

This section provides the steps required to monitor the progress of the campaigns.

[NOTE]
====
Before monitoring the progress, you must be authenticated to the {app-short-name} as an altiplano user.
Refer to xref:User_Guide:How_to_manage_ACCM_access.adoc[How to Manage {app-short-name} access] section for more details.
====

== Monitor the progress of a campaign

To get the progress of a campaign using the {app-short-name} REST API you must execute the following step:

. Send a GET request to the following URL:
link:https://{altiplano-host}/{accm-api-context}/campaigns/<CAMPAIGN_NAME>/progress[https://{altiplano-host}/{accm-api-context}/campaigns/<CAMPAIGN_NAME>/progress,window=_blank]
+
Path Variable::
+
* *CAMPAIGN_NAME*: It is the string that identifies the campaign.
+
Body::
The request body must be empty.
+
For example:: A GET request must be sent to the following URL: https://{ip-host-example}/{accm-api-context}/campaigns/CAMP/progress

=== Response example for a scheduled campaign

[source, json]
----
{
    "name": "CAMP",
    "status": "Scheduled",
    "totalElements": 3,
    "updatedElements": 0,
    "downloadedElements": 0,
    "progress": [
        {
            "operation": "Download",
            "progress": 0.0
        },
        {
            "operation": "Upgrade",
            "progress": 0.0
        }
    ],
    "clusters": [
        {
            "clusterName": "LSN.2MF2",
            "totalElements": 3,
            "updatedElements": 0,
            "downloadedElements": 0,
            "status": "Scheduled",
            "apAdditionalInformationURL": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2",
            "progress": [
                {
                    "operation": "Download",
                    "progress": 0.0
                },
                {
                    "operation": "Upgrade",
                    "progress": 0.0
                }
            ],
            "elements": [
                {
                    "elementType": "Headend",
                    "elements": [
                        {
                            "name": "Subtended_FX16",
                            "status": "Scheduled",
                            "progress": [
                                {
                                    "operation": "Download",
                                    "progress": 0.0
                                },
                                {
                                    "operation": "Upgrade",
                                    "progress": 0.0
                                }
                            ],
                            "apAdditionalInformation": [
                                {
                                    "operation": "Download",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_DL/devices/Subtended_FX16"
                                },
                                {
                                    "operation": "Upgrade",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_UPG_HE/devices/Subtended_FX16"
                                }
                            ],
                            "operations": [
                                {
                                    "operation": "Download"
                                },
                                {
                                    "operation": "Upgrade"
                                }
                            ]
                        }
                    ]
                },
                {
                    "elementType": "RemoteOLT",
                    "elements": [
                        {
                            "name": "Subtended_MF21",
                            "status": "Scheduled",
                            "progress": [
                                {
                                    "operation": "Download",
                                    "progress": 0.0
                                },
                                {
                                    "operation": "Upgrade",
                                    "progress": 0.0
                                }
                            ],
                            "apAdditionalInformation": [
                                {
                                    "operation": "Download",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_DL/devices/Subtended_MF21"
                                },
                                {
                                    "operation": "Upgrade",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_UPG_OLTB_1/devices/Subtended_MF21"
                                }
                            ],
                            "operations": [
                                {
                                    "operation": "Download"
                                },
                                {
                                    "operation": "Upgrade"
                                }
                            ]
                        },
                        {
                            "name": "Subtended_MF22",
                            "status": "Scheduled",
                            "progress": [
                                {
                                    "operation": "Download",
                                    "progress": 0.0
                                },
                                {
                                    "operation": "Upgrade",
                                    "progress": 0.0
                                }
                            ],
                            "apAdditionalInformation": [
                                {
                                    "operation": "Download",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_DL/devices/Subtended_MF22"
                                },
                                {
                                    "operation": "Upgrade",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_UPG_OLTB_2/devices/Subtended_MF22"
                                }
                            ],
                            "operations": [
                                {
                                    "operation": "Download"
                                },
                                {
                                    "operation": "Upgrade"
                                }
                            ]
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Headend",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade RemoteOLT batch 1",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade RemoteOLT batch 2",
                    "status": "Scheduled"
                }
            ]
        }
    ]
}
----

=== Response example for a executing campaign

[source, json]
----
{
    "name": "CAMP",
    "status": "Executing",
    "totalElements": 1,
    "updatedElements": 0,
    "downloadedElements": 0,
    "progress": [
        {
            "operation": "Download",
            "progress": 0.0
        },
        {
            "operation": "Upgrade",
            "progress": 0.0
        }
    ],
    "clusters": [
        {
            "clusterName": "LSN.FX16",
            "totalElements": 1,
            "updatedElements": 0,
            "downloadedElements": 0,
            "status": "NotScheduled",
            "apAdditionalInformationURL": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.FX16",
            "progress": [
                {
                    "operation": "Download",
                    "progress": 0.0
                },
                {
                    "operation": "Upgrade",
                    "progress": 0.0
                }
            ],
            "elements": [
                {
                    "elementType": "Headend",
                    "elements": [
                        {
                            "name": "Standalone_FX16",
                            "status": "NotScheduled",
                            "progress": [
                                {
                                    "operation": "Download",
                                    "progress": 0.0
                                },
                                {
                                    "operation": "Upgrade",
                                    "progress": 0.0
                                }
                            ],
                            "apAdditionalInformation": [
                                {
                                    "operation": "Download",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.FX16/activities/CAMP_LSN.FX16_DL/devices/Standalone_FX16"
                                },
                                {
                                    "operation": "Upgrade",
                                    "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.FX16/activities/CAMP_LSN.FX16_UPG_HE/devices/Standalone_FX16"
                                }
                            ],
                            "operations": [
                                {
                                    "operation": "Download"
                                },
                                {
                                    "operation": "Upgrade"
                                }
                            ]
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "NotScheduled"
                },
                {
                    "name": "Upgrade Headend",
                    "status": "NotScheduled"
                }
            ]
        }
    ]
}
----

=== Response example for a success campaign

[source, json]
----
{
  "name": "CAMP",
  "status": "Success",
  "totalElements": 2,
  "updatedElements": 2,
  "downloadedElements": 2,
  "startedAt": "2026-07-21T11:50:01",
  "endedAt": "2026-07-21T11:55:23",
  "progress": [
    {
      "operation": "Download",
      "progress": 100
    },
    {
      "operation": "Upgrade",
      "progress": 100
    }
  ],
  "clusters": [
    {
      "clusterName": "LSN.2MF2",
      "totalElements": 2,
      "updatedElements": 2,
      "downloadedElements": 2,
      "status": "Success",
      "startedAt": "2026-07-21T11:50:01",
      "endedAt": "2026-07-21T11:55:23",
      "apAdditionalInformationURL": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2",
      "progress": [
        {
          "operation": "Download",
          "progress": 100
        },
        {
          "operation": "Upgrade",
          "progress": 100
        }
      ],
      "elements": [
        {
          "elementType": "RemoteOLT",
          "elements": [
            {
              "name": "Subtended_MF21",
              "status": "Success",
              "progress": [
                {
                  "operation": "Download",
                  "progress": 100
                },
                {
                  "operation": "Upgrade",
                  "progress": 100
                }
              ],
              "apAdditionalInformation": [
                {
                  "operation": "Download",
                  "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_DL/devices/Subtended_MF21"
                },
                {
                  "operation": "Upgrade",
                  "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_UPG_OLTB_1/devices/Subtended_MF21"
                }
              ],
              "operations": [
                {
                  "operation": "Download",
                  "startedAt": "2026-07-21T11:50:01",
                  "endedAt": "2026-07-21T11:50:04"
                },
                {
                  "operation": "Upgrade",
                  "startedAt": "2026-07-21T11:53:06",
                  "endedAt": "2026-07-21T11:53:06"
                }
              ]
            },
            {
              "name": "Subtended_MF22",
              "status": "Success",
              "progress": [
                {
                  "operation": "Download",
                  "progress": 100
                },
                {
                  "operation": "Upgrade",
                  "progress": 100
                }
              ],
              "apAdditionalInformation": [
                {
                  "operation": "Download",
                  "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_DL/devices/Subtended_MF22"
                },
                {
                  "operation": "Upgrade",
                  "url": "https://100.121.38.81/nokia-altiplano-ac/software-management/#/campaigns/CAMP_LSN.2MF2/activities/CAMP_LSN.2MF2_UPG_OLTB_2/devices/Subtended_MF22"
                }
              ],
              "operations": [
                {
                  "operation": "Download",
                  "startedAt": "2026-07-21T11:50:01",
                  "endedAt": "2026-07-21T11:50:04"
                },
                {
                  "operation": "Upgrade",
                  "startedAt": "2026-07-21T11:55:23",
                  "endedAt": "2026-07-21T11:55:23"
                }
              ]
            }
          ]
        }
      ],
      "executionSteps": [
        {
          "name": "Download",
          "status": "Success"
        },
        {
          "name": "Upgrade RemoteOLT batch 1",
          "status": "Success"
        },
        {
          "name": "Upgrade RemoteOLT batch 2",
          "status": "Success"
        }
      ]
    }
  ]
}
----

==== Response schemas

===== CampaignProgressSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| name | string | Campaign name
| status | Status | Current status for campaign
| total-elements | int | Elements to be updated (sum of all cluster elements)
| updated-elements | int | Current elements updated (sum of all updated cluster elements)
| downloaded-elements | int | Current elements downloaded (sum of all downloaded cluster elements)
| progress | Array<ProgressSchema> | Progress detail for each stage of the upgrade process
| started-at | date-time | Date and time when the campaign started its execution
| ended-at | date-time | Date and time when the campaign ended its execution
| clusters | Array<ClusterProgressSchema> | List of associated clusters for the campaign and their current progress
|===

===== ClusterProgressSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| cluster-name | string | Cluster name
| status | Status | Current status for cluster
| totalElements | int | Elements to be updated
| updatedElements | int | Current elements updated
| downloaded-elements | int | Current elements downloaded
| progress | Array<ProgressSchema> | Progress detail for each stage of the upgrade process
| started-at | date-time | Date and time when the cluster started its execution
| ended-at | date-time | Date and time when the cluster ended its execution
| elements | Array<ClusterElementTypeProgress> | List of element types for a cluster
| executionSteps | Array<ExecutionStepSchema> | List of steps (activities on Altiplano) and their status.
| ap-additional-information-url | string | URL to the Altiplano campaign corresponding to this cluster.

|===

===== ClusterElementTypeProgress
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| elementType | string | Classification of the element within the cluster topology. For Leaf/Spine clusters, the element types are Spine, CP Leaves, Access Leaves, and ONTs. For Standalone clusters, the element types are Headend OLT, Remote OLT, and ONTs. The ONT element types will only be available for campaigns associated with an "ONT Only” software matrix.
| elements | Array<ClusterElementProgress> | List of elements (devices or ONTs) belonging to the cluster's elementType.
|===

===== ClusterElementProgress
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| name | string | Element’s name (device or ONT)
| status | Status | Status for the element (Content provided through Altiplano's statusPerDevice endpoint.)
| progress | Array<ProgressSchema> | Progress detail for each stage of the upgrade process
| ap-additional-information | Array<ApAdditionalInformationSchema> | List of URLs with element details in Altiplano for each operation
| operations | Array<OperationSchema> | List of operations with start and end date and time executed on the element
|===

===== ProgressSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| operation | Enum | Download, Upgrade or Rollback
| progress | float | Percentage of progress of the operation
|===

===== ApAdditionalInformationSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| operation | Enum | Download, Upgrade or Rollback
| url | string | URL to the Altiplano element detail corresponding to this element and operation
|===

===== OperationSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| operation | Enum | Download, Upgrade or Rollback
| started-at | date-time | Date and time when the cluster started its execution
| ended-at | date-time | Date and time when the cluster ended its execution
|===

===== ExecutionStepSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| name | String | Name of the execution step
| status | Status | Current status of the execution step.
|===

===== Status (Enum)
*Type:* string

* NotScheduled
* Scheduled
* Executing
* Success
* Error
* ExecutingRollback
* RollBacked
* RollBackError
* Canceled

[NOTE]
====
Refer to xref:Statuses_Overview.adoc[Statuses Overview] section for more details about Campaigns, Clusters and Elements status.
====

== REST Error Responses
.Error response
[source,json]
----
{
  "timestamp": {isoDateTimestamp},
  "operationName": {operationName},
  "serviceName": {serviceName},
  "errorCode": {errorCode},
  "message": {message},
  "detail": []
}
----

=== ACCM-AC-0001

==== HTTP error code
500 Internal server error

==== Message
Internal error

==== Description
This error is thrown when any anomalous runtime situation occurs that was not contemplated. To avoid exposing an unhandled root cause, it is wrapped in a generic error of this type. The situations in which it is generated cannot be changed by the operator and need to be reported.

=== ACCM-AC-0004

==== HTTP error code
401 Unauthorized

==== Message
Access token is not valid anymore

==== Description
When the authorization token is invalid and must be updated

=== ACCM-AC-0011

==== HTTP error code
404 Not found

==== Message
Campaign \{campaignName} does not exist.

==== Description
When attempting to retrieve the campaign for update, detail, or action services, and it does not exist.

include::ROOT:go-back-component.adoc[Back]