include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= How to configure Software Matrices

== Introduction

This section provides the steps required to manage the software matrices in the {app-short-name}.

[NOTE]
====
Since the Software Matrix module endpoints act as a proxy for Altiplano's Target Solutions endpoints, they utilize the same schemas. Their descriptions can be found at https://documentation.nokia.com/aces/htdocs/3JL-08002-BMAA-PNZZA/NBI_263/NBI/main/NBI/using-access-controller/SoftwareManagement.html[Nokia's documentation]
====

[NOTE]
====
Before managing software matrices, you must be authenticated to the {app-short-name} as an altiplano user.
Refer to xref:User_Guide:How_to_manage_ACCM_access.adoc[How to Manage {app-short-name} access] section for more details.
====

== Create Software Matrix
To create a software matrix using the {app-short-name} REST API, you must execute the following step:

. Send a POST request to the following URL:
link:https://{altiplano-host}/{accm-api-context}/software-matrices[https://{altiplano-host}/{accm-api-context}/software-matrices,window=_blank]
+
Body::
+
The request must contain the following JSON body:
+
[source, json]
----
{
    "name": "{swMatrixName}",
    "target-solution-type": "{swMatrixType}",
    "target-solution-info": "{swMatrixInfo}"
}
----
- *name:* _(string)_ Name that identifies the software matrix.
- *target-solution-type:* _(string)_ Software Matrix. Possible values are: "device", "device-ont" or "ont".
- *target-solution-info:* _(stringified JSON array)_ It contains a serialized collection of objects that define the specific hardware configuration and software mapping for the solution. You must ensure the JSON content is properly escaped as a single string before including it in the request body.

For example - Example 1:: If you want to create a software matrix for the type "device-ont", a POST request with body must be sent to the following URL: https://{ip-host-example}/{accm-api-context}/software-matrices
+
[source, json]
----
{
    "name" : "SWMatrix1",
    "target-solution-type" : "device-ont",
    "target-solution-info" : [
    {
        "hardware-type": "LS-FX-FANT-H-FX16",
        "target-software": {
        "swFileFullPath": "default-https:multi-board-package/FX16/FX16",
        "display": "FX16"
        },
        "device-family": "composite-device",
        "support-offline-migration": true,
        "device-version": "25.9",
        "target-onu-software-mapping": [],
        "target-release": {
        "swFileFullPath": "default-https:onu-software/R26.04.00/R26.04.00",
        "display": "R26.04.00"
        }
    },
    {
        "hardware-type": "LS-MF-LMNT-B",
        "target-software": {
        "swFileFullPath": "default-https:multi-board-package/MF2/MF2",
        "display": "MF2"
        },
        "device-family": "composite-device",
        "support-offline-migration": true,
        "device-version": "25.9",
        "target-onu-software-mapping": [],
        "target-release": {
        "swFileFullPath": "default-https:onu-software/R26.04.00/R26.04.00",
        "display": "R26.04.00"
        }
    }
        ]
    }
----

[NOTE]
====
The access token of the user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_ACCM_access.adoc[REST APIs] section.
====

== Delete Software Matrix
To delete a software matrix using the {app-short-name} REST API, you must execute the following step:

. Send a DELETE request to the following URL:
link:https://{altiplano-host}/{accm-api-context}/software-matrices/<SOFTWARE_MATRIX_NAME>[https://{altiplano-host}/{accm-api-context}/software-matrices/<SOFTWARE_MATRIX_NAME>,window=_blank]
+
Path Variable::
+
* *SOFTWARE_MATRIX_NAME*: It is the string that identifies the software matrix.
+
Body::
The request body must be empty.
+
For example:: A DELETE request must be sent to the following URL: https://{ip-host-example}/{accm-api-context}/software-matrices/SWMatrix1

[NOTE]
====
The access token of the user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_ACCM_access.adoc[REST APIs] section.
====


== Get Software Matrix
To get a software matrix using the {app-short-name} REST API, you must execute the following step:

. Send a GET request to the following URL:
link:https://{altiplano-host}/{accm-api-context}/software-matrices/<SOFTWARE_MATRIX_NAME>[https://{altiplano-host}/{accm-api-context}/software-matrices/<SOFTWARE_MATRIX_NAME>,window=_blank]
+
Path Variable::
+
* *SOFTWARE_MATRIX_NAME*: It is the string that identifies the software matrix.
+
Body::
The request body must be empty.
+
For example:: A GET request must be sent to the following URL: https://{ip-host-example}/{accm-api-context}/software-matrices/SWMatrix1

[NOTE]
====
The access token of the user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_ACCM_access.adoc[REST APIs] section.
====

== Edit a Software Matrix
To edit a software matrix using the {app-short-name} REST API, you must execute the following step:

. Send a PATCH request to the following URL:
link:https://{altiplano-host}/{accm-api-context}/software-matrices/<SOFTWARE_MATRIX_NAME>[https://{altiplano-host}/{accm-api-context}/software-matrices/<SOFTWARE_MATRIX_NAME>,window=_blank]
+
Path Variable::
+
* *SOFTWARE_MATRIX_NAME*: It is the string that identifies the software matrix.
+
Body::
The request body must contain only the fields that wants to be modified
+
For example:: A PATCH request must be sent to the following URL: https://{ip-host-example}/{accm-api-context}/software-matrices/SWMatrix1
+
[source, json]
----
{
    "target-solution-type" : "device-ont",
    "target-solution-info" : [
    {
        "hardware-type": "LS-MF-LMNT-B",
        "target-software": {
        "swFileFullPath": "default-https:multi-board-package/MF2/MF2",
        "display": "MF2"
        },
        "device-family": "composite-device",
        "support-offline-migration": true,
        "device-version": "25.9",
        "target-onu-software-mapping": [],
        "target-release": {
        "swFileFullPath": "default-https:onu-software/R26.04.00/R26.04.00",
        "display": "R26.04.00"
        }
    }
        ]
    }
----

[NOTE]
====
The access token of the user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_ACCM_access.adoc[REST APIs] section.
====

== REST Error Responses
.Error response
[source,json]
----
{
  "timestamp": {isoDateTimestamp},
  "operationName": {operationName},
  "serviceName": {serviceName},
  "errorCode": {errorCode},
  "message": {message},
  "detail": []
}
----

=== ACCM-AC-0001

==== HTTP error code
500 Internal server error

==== Message
Internal error

==== Description
This error is thrown when any anomalous runtime situation occurs that was not contemplated. To avoid exposing an unhandled root cause, it is wrapped in a generic error of this type. The situations in which it is generated cannot be changed by the operator and need to be reported.

=== ACCM-AC-0004

==== HTTP error code
401 Unauthorized

==== Message
Access token is not valid anymore

==== Description
When the authorization token is invalid and must be updated

=== ACCM-AC-0005

==== HTTP error code
400 Bad Request

==== Message
Invalid software-matrix-type. Only types 'device-ont', 'ont', 'device' are allowed.

==== Description
When the software matrix being created or updated does not match the specified types.


include::ROOT:go-back-component.adoc[Back]