include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= How to monitor campaign progress

== Introduction

This section provides the steps required to monitor the progress of the campaigns.

[NOTE]
====
Before monitoring the progress, you must be authenticated to the {app-short-name} as an altiplano user.
Refer to xref:User_Guide:How_to_manage_ACCM_access.adoc[How to Manage {app-short-name} access] section for more details.
====

== Monitor the progress of a campaign

To get the progress of a campaign using the {app-short-name} REST API you must execute the following step:

. Send a GET request to the following URL:
link:https://{altiplano-host}/{accm-api-context}/campaigns/<CAMPAIGN_NAME>/progress[https://{altiplano-host}/{accm-api-context}/campaigns/<CAMPAIGN_NAME>/progress,window=_blank]
+
Path Variable::
+
* *CAMPAIGN_NAME*: It is the string that identifies the campaign.
+
Body::
The request body must be empty.
+
For example:: A GET request must be sent to the following URL: https://{ip-host-example}/{accm-api-context}/campaigns/CAMP/progress

=== Response example for a scheduled campaign

[source, json]
----
{
    "name": "CAMP",
    "status": "Scheduled",
    "clusters": [
        {
            "clusterName": "LSN",
            "totalElements": 10,
            "updatedElements": 0,
            "status": "Scheduled",
            "progress": 0,
            "elements": [
                {
                    "elementType": "Spines",
                    "elements": [
                        {
                            "name": "Condor_Spine1",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_Spine2",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_Spine3",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_Spine4",
                            "status": "Scheduled",
                            "progress": 0
                        }
                    ]
                },
                {
                    "elementType": "AccLeaves",
                    "elements": [
                        {
                            "name": "Condor_IXRS_1",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_2",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_3",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_4",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_5",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_6",
                            "status": "Scheduled",
                            "progress": 0
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 1",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 2",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 3",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 4",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 1",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 2",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 3",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 4",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 5",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 6",
                    "status": "Scheduled"
                }
            ]
        },
        {
            "clusterName": "LSN.2MF2",
            "totalElements": 1,
            "updatedElements": 0,
            "status": "Scheduled",
            "progress": 0,
            "elements": [
                {
                    "elementType": "RemoteOLT",
                    "elements": [
                        {
                            "name": "Subtended_MF22",
                            "status": "Scheduled",
                            "progress": 0
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade RemoteOLT batch 1",
                    "status": "Scheduled"
                }
            ]
        }
    ],
    "totalElements": 11,
    "updatedElements": 0,
    "progress": 0
}
----

=== Response example for a executing campaign

[source, json]
----
{
    "name": "CAMP",
    "status": "Executing",
    "clusters": [
        {
            "clusterName": "LSN",
            "totalElements": 10,
            "updatedElements": 0,
            "status": "Executing",
            "progress": 0,
            "elements": [
                {
                    "elementType": "Spines",
                    "elements": [
                        {
                            "name": "Condor_Spine1",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_Spine2",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_Spine3",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_Spine4",
                            "status": "Scheduled",
                            "progress": 0
                        }
                    ]
                },
                {
                    "elementType": "AccLeaves",
                    "elements": [
                        {
                            "name": "Condor_IXRS_1",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_2",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_3",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_4",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_5",
                            "status": "Scheduled",
                            "progress": 0
                        },
                        {
                            "name": "Condor_IXRS_6",
                            "status": "Scheduled",
                            "progress": 0
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Executing"
                },
                {
                    "name": "Upgrade Spine 1",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 2",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 3",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade Spine 4",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 1",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 2",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 3",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 4",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 5",
                    "status": "Scheduled"
                },
                {
                    "name": "Upgrade AccLeaves batch 6",
                    "status": "Scheduled"
                }
            ]
        },
        {
            "clusterName": "LSN.2MF2",
            "totalElements": 1,
            "updatedElements": 0,
            "status": "Executing",
            "progress": 0,
            "elements": [
                {
                    "elementType": "RemoteOLT",
                    "elements": [
                        {
                            "name": "Subtended_MF22",
                            "status": "Scheduled",
                            "progress": 0
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Executing"
                },
                {
                    "name": "Upgrade RemoteOLT batch 1",
                    "status": "Scheduled"
                }
            ]
        }
    ],
    "totalElements": 11,
    "updatedElements": 0,
    "progress": 0
}
----

=== Response example for a success campaign

[source, json]
----
{
    "name": "CAMP",
    "status": "Success",
    "clusters": [
        {
            "clusterName": "LSN",
            "totalElements": 10,
            "updatedElements": 10,
            "status": "Success",
            "progress": 100,
            "elements": [
                {
                    "elementType": "Spines",
                    "elements": [
                        {
                            "name": "Condor_Spine1",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_Spine2",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_Spine3",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_Spine4",
                            "status": "Success",
                            "progress": 100
                        }
                    ]
                },
                {
                    "elementType": "AccLeaves",
                    "elements": [
                        {
                            "name": "Condor_IXRS_1",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_IXRS_2",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_IXRS_3",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_IXRS_4",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_IXRS_5",
                            "status": "Success",
                            "progress": 100
                        },
                        {
                            "name": "Condor_IXRS_6",
                            "status": "Success",
                            "progress": 100
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Success"
                },
                {
                    "name": "Upgrade Spine 1",
                    "status": "Success"
                },
                {
                    "name": "Upgrade Spine 2",
                    "status": "Success"
                },
                {
                    "name": "Upgrade Spine 3",
                    "status": "Success"
                },
                {
                    "name": "Upgrade Spine 4",
                    "status": "Success"
                },
                {
                    "name": "Upgrade AccLeaves batch 1",
                    "status": "Success"
                },
                {
                    "name": "Upgrade AccLeaves batch 2",
                    "status": "Success"
                },
                {
                    "name": "Upgrade AccLeaves batch 3",
                    "status": "Success"
                },
                {
                    "name": "Upgrade AccLeaves batch 4",
                    "status": "Success"
                },
                {
                    "name": "Upgrade AccLeaves batch 5",
                    "status": "Success"
                },
                {
                    "name": "Upgrade AccLeaves batch 6",
                    "status": "Success"
                }
            ]
        },
        {
            "clusterName": "LSN.2MF2",
            "totalElements": 1,
            "updatedElements": 1,
            "status": "Success",
            "progress": 100,
            "elements": [
                {
                    "elementType": "RemoteOLT",
                    "elements": [
                        {
                            "name": "Subtended_MF22",
                            "status": "Success",
                            "progress": 100
                        }
                    ]
                }
            ],
            "executionSteps": [
                {
                    "name": "Download",
                    "status": "Success"
                },
                {
                    "name": "Upgrade RemoteOLT batch 1",
                    "status": "Success"
                }
            ]
        }
    ],
    "totalElements": 11,
    "updatedElements": 11,
    "progress": 100
}
----

==== Response schemas

===== CampaignProgressSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| name | string | Campaign name
| status | Status | Current status for campaign
| total-elements | int | Elements to be updated (sum of all cluster elements)
| updated-elements | int | Current elements updated (sum of all updated cluster elements)
| progress | float | Relation in percent between total and updated
| clusters | Array<ClusterProgressSchema> | List of associated clusters for the campaign and their current progress
|===

===== ClusterProgressSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| cluster-name | string | Cluster name
| status | Status | Current status for cluster
| totalElements | int | Elements to be updated
| updatedElements | int | Current elements updated
| progress | float | Relation in percent between total and updated
| elements | Array<ClusterElementTypeProgress> | List of element types for a cluster
| executionSteps | Array<ExecutionStepSchema> | List of steps (activities on Altiplano) and their status.
|===

===== ClusterElementTypeProgress
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| elementType | string | Classification of the element within the cluster topology. For Leaf/Spine clusters, the element types are Spine, CP Leaves, Access Leaves, and ONTs. For Standalone clusters, the element types are Headend OLT, Remote OLT, and ONTs. The ONT element types will only be available for campaigns associated with an "ONT Only” software matrix.
| elements | Array<ClusterElementProgress> | List of elements (devices or ONTs) belonging to the cluster's elementType.
|===

===== ClusterElementProgress
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| name | string | Element’s name (device or ONT)
| status | Status | Status for the element (Content provided through Altiplano's statusPerDevice endpoint.)
| progress | float | Value obtained through Altiplano's statusPerDevice endpoint.
|===

===== ExecutionStepSchema
[cols="1,1,2", options="header"]
|===
| Attribute | Type | Description
| name | String | Name of the execution step
| status | Status | Current status of the execution step.
|===

===== Status (Enum)
*Type:* string

* NotScheduled
* Scheduled
* Executing
* Success
* Error
* ExecutingRollback
* RollBacked
* RollBackError
* Canceled

[NOTE]
====
Refer to xref:Statuses_Overview.adoc[Statuses Overview] section for more details about Campaigns, Clusters and Elements status.
====

== REST Error Responses
.Error response
[source,json]
----
{
  "timestamp": {isoDateTimestamp},
  "operationName": {operationName},
  "serviceName": {serviceName},
  "errorCode": {errorCode},
  "message": {message},
  "detail": []
}
----

=== ACCM-AC-0001

==== HTTP error code
500 Internal server error

==== Message
Internal error

==== Description
This error is thrown when any anomalous runtime situation occurs that was not contemplated. To avoid exposing an unhandled root cause, it is wrapped in a generic error of this type. The situations in which it is generated cannot be changed by the operator and need to be reported.

=== ACCM-AC-0004

==== HTTP error code
401 Unauthorized

==== Message
Access token is not valid anymore

==== Description
When the authorization token is invalid and must be updated

=== ACCM-AC-0011

==== HTTP error code
404 Not found

==== Message
Campaign \{campaignName} does not exist.

==== Description
When attempting to retrieve the campaign for update, detail, or action services, and it does not exist.

include::ROOT:go-back-component.adoc[Back]